### PR TITLE
Remove the ignoreInsecureRoot flag

### PR DESCRIPTION
**Pull request by leofeyer**
This PR removes the `ignoreInsecureRoot` flag as discussed in Ahrweiler. @contao/developers Please vote.

### CODE REVIEW

**Comment by Toflar** [comment]
Oh, I need to fix my document root then :D Good to merge imho :+1:

**Comment by leofeyer** [comment]
I'd suggest to make it an event listener eventually then it could be deactivated by removing the listener.

**Comment by Toflar** [comment]
No, it's a security issue. I think we should force people to properly configure their setups :)

**Comment by ausi** [comment]
Would it still be possible to run Contao in a subfolder on an apache server with a customized htaccess?

**Comment by leofeyer** [comment]
@ausi That depends on what you mean by "customized htaccess".

**Comment by aschempp** [comment]
Ich denke sowas wie Variant 1 von https://www.cyon.ch/support/a/210/kann-ich-eine-domain-aus-einem-unterordner-aufrufen ist gemeint

**Comment by ausi** [comment]
Something like this to run contao in `example.com/my-subfolder`:

```
RewriteEngine on
RewriteBase /my-subfolder
RewriteRule (.*) /web/app.php%{REQUEST_URI} [L]
```

**Comment by leofeyer** [comment]
Das müsste man testen.

**Comment by aschempp** [comment]
As I commented previously, the saying of "not relying on .htaccess" is wrong. We still need .htaccess or a similar method (e.g. for Nginx) for URL rewriting, otherwise the `app.php` remains in the URL. There's no difference to Contao 3.

**Comment by leofeyer** [comment]
The wording is correct. We have been relying on `.htaccess` files in Contao 3 and we are no longer in Contao 4. Of course your web server needs to support URL rewriting, but you do not necessarily need an `.htaccess` file for it - not even on Apache ;)

**Comment by aschempp** [comment]
Where did we rely on `.htaccess` files in Contao 3 except for URL rewriting?

**Comment by leofeyer** [comment]
Folder protection in `/files`?

**Comment by aschempp** [comment]
Aah, forgot about that. I still think it's misleading as most people used `.htaccess` for URL rewriting. Maybe the text could say something like that:

> Contao 4 does no longer rely on `.htaccess` for file access control but uses a public subfolder as document root instead. …`

**Comment by Toflar** [comment]
And I think it should say

`[...]a public subfolder (by default "web") as document [...]`

instead. :)

**Comment by leofeyer** [comment]
@aschempp I have adjusted the wording in 51021d1333c9c8916b5129cb94fc6e45a035a476.

@Toflar If we'd say "by default" people would assume they could change the folder. However they cannot, because references to `/web` are currently hardcoded. We might change this of course but that would be a separate feature.

Can I merge the PR now?

**Comment by aschempp** [comment]
I think it should be *but* instead of *and*, maybe a native speaker can review the sentence?

> Contao 4 does no longer rely on `.htaccess` files to protect folders and uses a public subfolder as document root instead. Anything above the document root must not be accessible via HTTP, otherwise anyone could download non-public resources including sensible data such as configuration files.

/cc @BlairWinans

**Comment by leofeyer** [comment]
Changed and merged in 9da41d6608a52b53eb20b02eafdb17de27ccddc2.

**Comment by blairwinans** [comment]
Just seeing this now—if you want it to make the most sense in EN, I would say:

>Contao 4 no longer relies on .htaccess files to protect folders, and instead uses a public subfolder as document root instead. Anything above the document root must not be accessible via HTTP, otherwise anyone could download non-public resources including sensitive data such as configuration files.

**Pull request merged**
