### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by bytehead**
According to https://github.com/contao/core-bundle/community

### CODE REVIEW

**Comment by leofeyer** [comment]
Why? The license text is already shown in the install tool and no-one will read the `LICENSE` file deep down in `vendor/contao/core-bundle`. I'm against adding it.

**Comment by bytehead** [comment]
Because it's a de facto standard and GitHub will display it as well:
bildschirmfoto 2018-01-12 um 17 48 06

**Comment by leofeyer** [comment]
I know. It is still pointless IMHO.

**Comment by leofeyer** [comment]
> Because it's a de facto standard and GitHub will display it as well:

@bytehead Hm … https://github.com/1up-lab/OneupUploaderBundle

**Comment by bytehead** [comment]
I know, it'a pending task 😆

**Comment by aschempp** [comment]
I'm **pro** adding this, it's not about the distributed version but about the GitHub repo.

**Comment by bytehead** [comment]
Added in 483e7fe6da764f152935308bb8117f5d602290df.

**Pull request closed without merging**
