### PR TITLE
[RFC] Add article tree widget

### PR DESCRIPTION
**Pull request by agoat**
This PR adds an article tree widget to complete/extend the new dcaPicker. 

This can be used in the DCA like the `pageTree` (multiple and rootNodes are also supported) to select articles with the new picker.

I'm not sure if the content elements `Article` and `Article teaser` should use the articleTree. All other `Include elements` use select fields by now.

### CODE REVIEW

**Comment by agoat** [comment]
There is a problem with the rootNodes handling (#see #1001). This have to be considered here, too.

**Comment by agoat** [comment]
Note for me: Set the radio button as default (see #989).

**Comment by Toflar** [comment]
@agoat I like the PR although I have currently no use case for it :) But you never know ;) It is currently not yet tagged for 4.5 because tests are failing. Maybe you need to rebase to latest develop?

**Comment by agoat** [comment]
> I have currently no use case for it

We could use it in the `article` and `article teaser` content elements. The `article teaser` limit the selection to the articles from the same root. This can be done here, too, since the correct root node handling (see #1001) is merged.

And I use it already in an extension (special branch together with an adjusted core-bundle).

**Comment by Toflar** [comment]
I never use that feature but then I guess you should include the changes to tl_content already :)

**Comment by leofeyer** [comment]
Can you please post a screenshot of the article picker in action?

**Comment by leofeyer** [comment]
See contao/contao#714

**Pull request closed without merging**
