### PR TITLE
Local exceptions for PaletteManipulator

### PR DESCRIPTION
**Pull request by aschempp**
Replaces #524

### CODE REVIEW

**Comment by leofeyer** [comment]
As discussed, the nested try-catch blocks need to be added everywhere else where we are using the file locator.

**Comment by leofeyer** [comment]
I think the code could be simplified as follows:

```php
// Now
$blnBubble = false;

try
{
	foreach (\System::getContainer()->get('contao.resource_locator')->locate('dca/' . $this->strTable . '.php', null, false) as $file)
	{
		try
		{
			include $file;
		}
		catch (\InvalidArgumentException $e)
		{
			$blnBubble = true;
			throw $e;
		}
	}
}
catch (\InvalidArgumentException $e)
{
	// Re-throw the InvalidArgumentException if it has originated from a DCA file
	if ($blnBubble)
	{
		throw $e;
	}
}
```

```php
// Then
try
{
	$files = \System::getContainer()->get('contao.resource_locator')->locate('dca/' . $this->strTable . '.php', null, false);
}
catch (\InvalidArgumentException $e)
{
	$files = null;
}

if ($files !== null)
{
	foreach ($files as $file)
	{
		include $file;
	}
}
```

@aschempp What do you think?

**Comment by aschempp** [comment]
very good idea. If you assign an empty array instead of `null` you can even skip the `if` statement :-)

**Comment by leofeyer** [comment]
Exactly what I though right now. 😄

**Comment by leofeyer** [comment]
Merged in ef216e9f8442ce90fa8988a6a623a7a77ca1307e.

**Pull request closed without merging**
