### PR TITLE
[RTM] Extract bundle code

### PR DESCRIPTION
**Pull request by aschempp**
There are various places where the current core bundle that is still related to other bundles that must not necessarily be installed.

**Corresponding PRs:**
NewsBundle: https://github.com/contao/news-bundle/pull/4
CalendarBundle: https://github.com/contao/calendar-bundle/pull/3
FaqBundle: https://github.com/contao/faq-bundle/pull/2

If we can quickly agree on the general approach (listener with DI for hook callback etc.) I will continue migration other stuff like insert tags.

### CODE REVIEW

**Comment by Toflar** [comment]
Fine for me! Except for using our own `Database` class. This should not be done anymore.

**Comment by aschempp** [comment]
Unfortunately the hook expects a `Database\Result` as return value, so there's no way around that. I don't think we should refactor the core class just for that.

**Comment by aschempp** [comment]
I've extracted all remaining functionality. There are now several translations still in `core-bundle`, but afaik they will automatically be dropped on Transifex sync.

**Comment by leofeyer** [comment]
Merged in 24167cf3871be7365274acc47f68079ba015d0e5.

@aschempp There are still some places where the core uses extension code:

* https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/library/Contao/InsertTags.php#L522-L530
* https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/dca/tl_member.php#L744-L755

I figure you left them in because you did not want to add new hooks, am I right?

**Comment by aschempp** [comment]
Certainly true for the insert tag. We might be able to move the newsletter stuff by using a `save_callback`? Must have not noticed that…

**Comment by leofeyer** [comment]
The `last_update` insert tag is a fail by design anyway, because it only supports three tables out of five or six possible ones and it is not extendable. We should fix this. On the other hand, the insert tag seems pretty useless to me in the first place ;)

**Comment by Toflar** [comment]
It is pretty useless anyway, let's face it. Even if e.g. Isotope was able to modify this through an event, what's the point in showing the last modification date on a page that does not display any Isotope data? The insert tag might be used completely out of context of the last modification date. We can as well just drop it/let it show the last modification date of the articles only.

**Comment by aschempp** [comment]
I'm pretty sure it was added because people want to show that. And they are currently using it, so we should not simply remove. But I would deprecated it for Contao 5 and not fix anything for now…

**Comment by leofeyer** [comment]
Fixed the newsletter sync callback in f94f556e880025cf1aec9de697965cc250ad7143 and contao/newsletter-bundle@32976e97d9e895968d8d036f29ab0b6330ce822d.

**Comment by aschempp** [comment]
Why are you adding code to the legacy classes and not create a correct listener? Want me to PR?

**Comment by leofeyer** [comment]
It was not worth the effort IMHO. But feel free to create a PR :)

**Pull request merged**
