### PR TITLE
[RTM] Set Contao encryption key from kernel secret by default

### PR DESCRIPTION
**Pull request by aschempp**
Dunno why we didn't add that in the first place. This will make https://github.com/contao/standard-edition/blob/master/app/config/config.yml#L29 obsolete.

### CODE REVIEW

**Comment by leofeyer** [comment]
Then we can also omit `encryption_key: "%kernel.secret%"` in the `config.yml` file, right?

**Comment by aschempp** [comment]
Itsn't that what I linked above? 😂

**Comment by leofeyer** [comment]
So while we are at this, why don't we do the same for the `contao.prepend_locale` parameter? Then we could remove the entire Contao configuration from the `config.yml` file.

**Comment by leofeyer** [comment]
Actually, this can be done even more simple:

```php
        $rootNode
            ->children()
                ->booleanNode('prepend_locale')
                    ->defaultValue("%prepend_locale%")
                ->end()
                ->scalarNode('encryption_key')
                    ->cannotBeEmpty()
                    ->defaultValue("%kernel.secret%")
                ->end()
                // …
```

I don't know why we are using constructor injection here at all?

**Comment by leofeyer** [comment]
Ah, probably because we use `!$this->debug` instead of `$this->debug?`.

**Comment by leofeyer** [comment]
See my follow up PR: #664

**Comment by aschempp** [comment]
I have updated the PR.

**Pull request merged**
