### PR TITLE
[RFC] Update the DEPRECATED.md file

### PR DESCRIPTION
**Pull request by fritzmg**
I simply took the exact same wording from the `trigger_error` method [here](https://github.com/contao/core-bundle/blob/4.3.7/src/Resources/contao/library/Contao/System.php#L438).

It would be useful to provide some examples - however PHP files do not seem to work there currently (#740).

### CODE REVIEW

**Comment by fritzmg** [comment]
Agreed.

Am I right in assuming that any DCA changes should be done via `app/Resources/contao/…`?

Not sure what to write about the `initconfig.php` though other than it being deprecated.

**Comment by leofeyer** [comment]
Symfony provides a lot of useful events that can be used instead of the `initconfig.php` file.

**Comment by fritzmg** [comment]
Do you have a suitable example? I cannot think of a proper use-case for the `initconfig.php` right now anymore. I sometimes put things in there that could be done in the `dcaconfig.php` as well - but I chose to do it in the `initconfig.php` since it it only executed once.

**Comment by aschempp** [comment]
As far as I remember there is no Contao framework initialization event, but `kernel.request` might be used in most of the places for example.

**Comment by fritzmg** [comment]
I have updated the PR.

**Comment by leofeyer** [comment]
Merged in aae0a69798c6672dbcb9a6ef1192e9ed2f9a7c28.

**Pull request closed without merging**
