### PR TITLE
[RTM] Subsequent elseif should not match

### PR DESCRIPTION
**Pull request by ausi**
Follow up to #579, see contao/core#8491

### CODE REVIEW

**Comment by leofeyer** [comment]
Is this PR ready to merge? I figure we also need to back port the changes into the LTS version, don't we?

**Comment by Toflar** [comment]
> I figure we also need to back port the changes into the LTS version, don't we?

Sure, it is a pretty important fix.

**Comment by ausi** [comment]
> Is this PR ready to merge?

Yes, I think so.

**Comment by leofeyer** [comment]
Merged in 7589374a4332bd9aa1cdf47a7ecdcf19a5afb6a4 and back ported in contao/core@c5b9e81173a6aee14bac3d096c5e97d70e6a8dfe.

**Pull request closed without merging**
