### PR TITLE
[RTM] Feature/trusted proxy support

### PR DESCRIPTION
**Pull request by Toflar**
This is a PR for https://github.com/contao/core-bundle/issues/128. I checked the code and imho our legacy code does exactly what Symfony's `Request::getClientIp()` does.

Please double check this though :)

### CODE REVIEW

**Comment by aschempp** [comment]
I've noticed that too in https://github.com/contao/core-bundle/pull/72/files#diff-2f0eb5d18e0f5fb0dbaef526bb165d41R305

Should we add the `TL_CONFIG` variable for BC? We currently do that for all other variables, and I do have some customization where I use the variable.

**Comment by Toflar** [comment]
> Should we add the TL_CONFIG variable for BC? We currently do that for all other variables, and I do have some customization where I use the variable.

BC of what? What would it help to add the variable?

**Comment by aschempp** [comment]
I mean adding it here:
https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/library/Contao/Config.php#L484-L505

**Comment by Toflar** [comment]
But what does it help? It sets a TL_CONFIG value that is **never** used.

**Comment by aschempp** [comment]
We don't know if extension developers used it. Same with SMTP, it's unlikely someone used it because the `Email` class does automatically use it, but it would not harm to add it for the sake of completeness.

**Comment by Toflar** [comment]
But it's not really possible because we did not support all the notations `IpUtils` supports. One can configure an IP range in the trusted_proxy settings and we would need to resolve this to a list of comma separated IP's to set that value. I mean, of course it's possible but is it worth the effort?

**Comment by aschempp** [comment]
That's true, assuming people will start using IP ranges…

**Comment by leofeyer** [comment]
Looks good to me. Let me know when it is RTM :)

**Comment by Toflar** [comment]
Okay for you and @aschempp so it's RTM for me :)

**Comment by leofeyer** [comment]
Merging this will invalidate #128, right?

**Comment by Toflar** [comment]
Not invalidate but close :-)

**Comment by aschempp** [comment]
We should also close my PR in contao/core for ip-range support and mention this

**Comment by leofeyer** [comment]
Can you fix the tests please?

```
PHP Fatal error:  Call to a member function getContainer() on null in /var/www/contao/standard-edition/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Environment.php on line 376
```

The method is probably missing in our kernel mock.

**Comment by aschempp** [comment]
`global $kernel` is missing ;)

**Comment by Toflar** [comment]
Fixed. But now I have a new problem that's probably caused by some component overriding the `$_SERVER` or whatever. I can't find the issue...

**Comment by aschempp** [comment]
I guess here's the problem:
https://github.com/contao/core-bundle/blob/develop/tests/TestCase.php#L96

**Comment by Toflar** [comment]
True, why is this?

**Comment by aschempp** [comment]
I guess because a default value is alway necessary… 

Maybe we should change that to something like this:
```
if (empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
    $_SERVER['HTTP_ACCEPT_LANGUAGE'] = '';
}
```

**Comment by leofeyer** [comment]
I have no idea. I think the `mockKernel()` method is from @discordier?

**Comment by leofeyer** [comment]
Do the tests still work if you remove the line?

**Comment by discordier** [comment]
Having similar issues in my pr. Stay tuned. Will search a solution tomorrow.

**Comment by leofeyer** [comment]
I have fixed the tests and merged the PR in c375b7c3cb441565962e97493ba8bd7e594c9f28.

**Pull request merged**
