### PR TITLE
BC compat for tl_content::pagePicker

### PR DESCRIPTION
**Pull request by aschempp**
The `tl_content::pagePicker` method is used by any extension that wanted to add a page picker before Contao 4.4. I know `tl_content` is not a BC layer, but we sure should try to prevent such issues if we can…

### CODE REVIEW

**Comment by leofeyer** [comment]
You mean that people have added

```php
'wizard' => array
(
	array('tl_content', 'pagePicker')
),
```

in their DCAs?

**Comment by aschempp** [comment]
correct, on their custom fields in `tl_content`.

**Comment by aschempp** [comment]
I just fixed another bug in https://github.com/contao/core-bundle/pull/871/commits/ba30baaba92c7bf6b5450699293886a10d477ee4. On multi-edit the field name would result in duplicate ID attributes.

**Comment by leofeyer** [comment]
Merged in 480e16df58e88d62cf155b834d901d572bbd6cb8.

**Pull request closed without merging**
