### PR TITLE
implement changes to flexible theme

### PR DESCRIPTION
**Pull request by fritzmg**
This would implement the changes to the theme described here https://github.com/contao/core-bundle/issues/477#issuecomment-215989342

### CODE REVIEW

**Comment by leofeyer** [comment]
As you wrote yourself, this is a personal preference. I prefer the new look without the massive white sidebar, therefore I won't make any changes until the theme has been released and people have worked with it for a while. Then we can discuss anything.

**Comment by aschempp** [comment]
I like @fritzmg's ideas :-)

**Comment by fritzmg** [comment]
> As you wrote yourself, this is a personal preference. I prefer the new look without the massive white sidebar, therefore I won't make any changes until the theme has been released and people have worked with it for a while. Then we can discuss anything.

Yeah, I understand. I made the PR just in case.

**Comment by leofeyer** [comment]
Closing this in favor of #477.

**Pull request closed without merging**
