### PR TITLE
[RFC] Change contao.image.target_path to an absolute value

### PR DESCRIPTION
**Pull request by aschempp**
Fixed one issue mentioned in https://github.com/contao/core-bundle/issues/638

### CODE REVIEW

**Comment by leofeyer** [comment]
This is not correct unfortunately, as the end result should be `'%contao.root_dir%/assets/images'`.

**Comment by discordier** [comment]
Reopen and retarget? Was against contao:hotfix/4.3.1.

**Comment by leofeyer** [comment]
We can actually implement this if we use a different parameter name:

```php
                        ->scalarNode('target_dir')
                            ->defaultValue('%contao.root_dir%/assets/images')
                        ->end()
```

Then we can deprecate `contao.image.target_path` in favor of `contao.image.target_dir`.

**Comment by aschempp** [comment]
To be fully BC the default value would need to be `%kernel.root_dir%/%contao.image.target_path%`. But I don't like to create a new parameter just for that…

**Comment by leofeyer** [comment]
See #684.

**Pull request closed without merging**
