### PR TITLE
[RTM] Use the Composer autoloader to load the Contao classes

### PR DESCRIPTION
**Pull request by leofeyer**
This PR implements #437. @contao/developers Do we want it this way?

### CODE REVIEW

**Comment by aschempp** [comment]
That could work. We should also add a `@deprecated` to the `ClassLoader` to make sure people stop using it.

**Comment by Toflar** [comment]
And what about the `trigger_error()`?

**Comment by leofeyer** [comment]
I have not yet added the deprecation stuff, because I was not sure if you like the implementation. So do you want me to complete the PR?

**Comment by Toflar** [comment]
I think it looks good, yes.

**Comment by aschempp** [comment]
How will it behave if someone is currently overriding the global name of a class?

**Comment by leofeyer** [comment]
The PR is RTM now. Please review again.

**Comment by leofeyer** [comment]
Merged in 42661a616297b030f2e0952e7eaeca77ae8579a4.

**Pull request merged**
