### PR TITLE
Make sure no output buffer is active before download

### PR DESCRIPTION
**Pull request by antoinedavid**
#696

### CODE REVIEW

**Comment by leofeyer** [comment]
@contao/developers Do we also need to add this?

```php
		// Prevent session locking (see #2804)
		session_write_close();

		// Disable zlib.output_compression (see #6717)
		ini_set('zlib.output_compression', 'Off');
```

See [Contao/File.php#L802-L806](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/File.php#L802-L806)

**Comment by ausi** [comment]
I don’t think so. I’m also not sure if this is the right place for `ob_end_clean()` because we are throwing a `ResponseException` and do not output anything. Shouldn’t this be handled in the code that actually sends the output to the browser?

**Comment by leofeyer** [comment]
It probably should, but it is not. :confused:

**Comment by ausi** [comment]
> It probably should, but it is not. 😕

Why don’t we fix it there then?

**Comment by Toflar** [comment]
This fix is not correct in my opinion. The Symfony `Response` class closes buffers on `send()`.

**Comment by Toflar** [comment]
@antoinedavid You have to debug if the kernel does correctly handle our `ExceptionListener` that transforms the `ResponseException` to a `Response` and if your entry point (`app.php`) actually does call `$response->send()` on the correct response instance.

**Comment by antoinedavid** [comment]
> I don’t think so. I’m also not sure if this is the right place for ob_end_clean() because we are throwing a ResponseException and do not output anything. Shouldn’t this be handled in the code that actually sends the output to the browser?

In the detail of a news item the output is not empty when `sendToBrowser()` is executed. if you make a simple `dump() exit;` you will see you'r news detail before your dump().

I think `ob_end_clean()` is a temporary solution i think the issue is more complex. Unfortunately I do not have time at the moment to deepen my research.

**Comment by Toflar** [comment]
I tracked this down. So effectively Symfony makes sure, output buffers are closed AFTER the file is sent. We need to flush before we send it because we already have output buffers active. So turns out @antoinedavid's solution was correct, we should just reuse Symfony methods for that.
Here you go:

```diff
diff --git a/src/Resources/contao/library/Contao/File.php b/src/Resources/contao/library/Contao/File.php
index 7d150bf..8a87b79 100644
--- a/src/Resources/contao/library/Contao/File.php
+++ b/src/Resources/contao/library/Contao/File.php
@@ -14,6 +14,7 @@ use Contao\CoreBundle\Exception\ResponseException;
 use Contao\Image\Image as ContaoImage;
 use Contao\Image\ImageDimensions;
 use Symfony\Component\HttpFoundation\BinaryFileResponse;
+use Symfony\Component\HttpFoundation\Response;
 use Symfony\Component\HttpFoundation\ResponseHeaderBag;
 
 
@@ -775,6 +776,9 @@ class File extends \System
 	 */
 	public function sendToBrowser($filename='')
 	{
+		// Close previous output buffers but do not flush
+		Response::closeOutputBuffers(0, false);
+
 		$response = new BinaryFileResponse(TL_ROOT . '/' . $this->strFile);
 
 		$response->setContentDisposition
```

**Comment by ausi** [comment]
I’m still not sure if closing the buffers belongs to this method. What if I want to catch the `ResponseException` in my application and do something else with it? The buffers shouldn’t get closed then.

Where does the output buffer get opened? Shouldn’t it be handled there? Like so:

```php
ob_start();
try {
	// some code that might throw exceptions
}
finally {
	ob_end_clean();
}
```

**Comment by Toflar** [comment]
> Where does the output buffer get opened? Shouldn’t it be handled there? Like so:

In any template...

**Comment by leofeyer** [comment]
> Where does the output buffer get opened?

Everywhere where templates are rendered:

 * https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L914
 * https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/TemplateInheritance.php#L181

**Comment by ausi** [comment]
> Everywhere where templates are rendered

I think we should add `try-finally` blocks in these places. This would fix the output buffer for all types exceptions.

**Comment by leofeyer** [comment]
As briefly discussed, I have added a workaround in fd15a93be4da0425050bf8879f4f2d8bc0d321f8 and @ausi will work on a "real" solution for Contao 4.4.

**Comment by leofeyer** [comment]
See #714. Thank you @ausi.

**Pull request closed without merging**
