### PR TITLE
[WIP] Deprecate the Message class

### PR DESCRIPTION
**Pull request by leofeyer**
This is the follow-up PR to #445.

### CODE REVIEW

**Comment by leofeyer** [comment]
As discussed, this should rather be a service with an interface defining the methods to add and render messages.

**Comment by aschempp** [comment]
I wasn't part of the discussion, does that mean I can currently ignore the PR?

**Comment by aschempp** [comment]
Just as a quick note, `TL_MODE` would not work here as it does not equal `frontend` and `backend`.

**Comment by leofeyer** [comment]
You can ignore the PR. I have to rework it.

**Comment by Toflar** [comment]
That's still something that would be helpful, no?

**Comment by leofeyer** [comment]
Of course. I just have not had the time yet.

**Comment by leofeyer** [comment]
I'm closing this in favor of #1211.

**Pull request closed without merging**
