### PR TITLE
Fix URL encoding in XML sitemaps

### PR DESCRIPTION
**Pull request by ausi**
See #1085

### CODE REVIEW

**Comment by jankout** [comment]
I think that this concerns all special characters - e.g. with Czech special characters it does not work too.

**Comment by ausi** [comment]
This pull request should fix all special characters, not only german ones. Can you give an example wich Czech special characters still cause problems?

**Comment by jankout** [comment]
For example, one of the common characters: **_í_**. You can use following characters to see if it already works. 

**č, ř, š, í, á, é, ú, ů, ó, ň, ť, ď.** 

More characters for anther languages you can find [here](https://de.wikipedia.org/wiki/Liste_lateinischer_Alphabete#Von_A_bis_I_abgeleitete_Buchstaben).

**Comment by ausi** [comment]
I just tested this pull request with the alias `čřšíáéúůóňťď` and it did work fine.

**Comment by leofeyer** [comment]
@ausi Do we have to encode the sitemap URLs at all? If the browsers can handle `veröffentlichungen.html`, Google should be able to handle it in a `sitemap.xml` file as well, shouldn't it?

**Comment by ausi** [comment]
@leofeyer the [sitemap protocol](https://www.sitemaps.org/protocol.html#escaping) defines *“all URLs ... must be URL-escaped”*.

**Comment by leofeyer** [comment]
Merged in 2dbf3a3dd947ec2d655f4bc9f5c212493d9e415f.

**Pull request closed without merging**
