### PR TITLE
Update default.xlf

### PR DESCRIPTION
**Pull request by poddus**
fix grammatical errors in the language fallback error messages

### CODE REVIEW

**Comment by leofeyer** [comment]
I am pretty sure that the first two changes are wrong. Can you please explain your changes?

**Comment by poddus** [comment]
"pages", being plural, "have" instead of  "has".
reduced sentence:
"none of the pages have the option set"
vs.
"none of the pages has the option set"

**Comment by leofeyer** [comment]
You are right. Reducing the sentence makes it easier to see. 👍

**Comment by gmpf** [comment]
> "pages", being plural, "have" instead of "has".

This reasoning is not correct though. The question is whether the subject of the sentence is singular or plural, and "pages" alone is not the subject of the sentence. The way I understand the grammar in this case, "none" would be the determinant, and "none" can be singular or plural depending on the sense of the sentence.

Compare this to the German version, where it is
>Keiner der aktiven Website-Startpunkte ohne explizite DNS-Einstellungen wurde als Sprachen-Fallback definiert.

with "Keiner" and "wurde" indicating singular use.
>Keine der aktiven Website-Startpunkte ohne explizite DNS-Einstellungen wurden als Sprachen-Fallback definiert.

would also be correct, and it would be the equivalent of this suggested change. Note the slight change in meaning however.

**Comment by asaage** [comment]
https://www.englishforums.com/English/NoneHasOrNoneHave/cqjgq/post.htm

**Comment by leofeyer** [comment]
Thank you @poddus.

**Pull request merged**
