### PR TITLE
[RTM] Adds a catch-all route

### PR DESCRIPTION
**Pull request by aschempp**
fixes #64, so that all routes are now handled by the legacy code.

Be aware that the problem of https://github.com/contao/core/issues/7666 still exists.

### TODOs
 - [x] Rename the parameter from `{alias}` to something like `{_catch_all}`

### CODE REVIEW

**Comment by leofeyer** [comment]
This does not seem correct. We only need a route for `/` as it used to be in the old implementation of the loader. Why would we want `/foo.bar` to be handled by Contao?

**Comment by aschempp** [comment]
Because we want `/foo.bar` to be handled by the legacy code and redirected to the 404 page.

**Comment by leofeyer** [comment]
This is not the case in Contao 3. And I don't think it is wise to run **everything** through the PHP parser.

**Comment by aschempp** [comment]
> And I don't think it is wise to run everything through the PHP parser.

But that was the case with Contao 3, right? If we don't do that, we need to write Symfony code to handle these cases (e.g. forward to the fallback language).

PS: it does not mean non `.html` URL are forwarded, the URL rewriting will still ignore them by default.

**Comment by leofeyer** [comment]
> But that was the case with Contao 3, right?

No. Only HTML documents were rewritten.

**Comment by aschempp** [comment]
> Only HTML documents were rewritten.

That's not true. The `.htaccess` takes care of forwarding requests to the entry point script, and by default it only forwarded `.html`. But if you removed that, everything was handled by Contao.
Btw, if that would be true, the requests would still not be handled with my proposed change, because the legacy code is still the same ;-)

**Comment by leofeyer** [comment]
You could be right. Then we should at least name the route `contao_catchall` instead of `contao_root`.

**Comment by aschempp** [comment]
I named it `contao_root` because we use it to redirect people to the root page.

**Comment by leofeyer** [comment]
Yes, but that's misleading. Routes are not named after where they redirect. A `*_root` route usually relates to `/`.

**Comment by aschempp** [comment]
@contao/developers other opinions? To me `contao_root` is just fine as that's what we use the name for.

**Comment by Toflar** [comment]
I can't follow the discussion. Somebody needs to explain it to me tomorrow.

**Comment by leofeyer** [comment]
As discussed on Mumble on March, 25th, we want to add two routes: `contao_root`, which matches only `/` and `contao_catch_all`, which comes as last route and catches everything which has not been caught before.

**Comment by aschempp** [comment]
Changed to RFC

**Comment by leofeyer** [comment]
Looks good to me. Can we change the status to `RTM`?

**Comment by aschempp** [comment]
Changed, assuming noone else has something to say ;-)

**Pull request merged**
