### PR TITLE
[RTM] Use the RequestToken class to validate the Contao request token

### PR DESCRIPTION
**Pull request by leofeyer**
As discussed on Mumble, we should use the `RequestToken` class to validate the Contao request token to restore support for `disableRefererCheck`, `BYPASS_TOKEN_CHECK` and `requestTokenWhitelist`. This PR includes the necessary changes.

@contao/developers Please review.

### CODE REVIEW

**Comment by Toflar** [comment]
Why did you not use the adapter here now?

**Comment by leofeyer** [comment]
For what? The class is not injected, therefore we cannot mock it. It would be cool though, if I could inject the adapter, but that's not possible, is it?

**Comment by leofeyer** [comment]
I mean this:

```yml
services:
    contao.framework.request_token_adapter:
        class: Contao\CoreBundle\Framework\Adapter
        public: false
        arguments:
            - "Contao\\RequestToken"
```

But as far as I remember, this is exactly the use case we do **not** want, right?

**Comment by aschempp** [comment]
You should alway inject the `ContaoFramework` and call `getAdapter()`!

**Comment by leofeyer** [comment]
This is something we should discuss.

**Comment by aschempp** [comment]
That was the whole point of adapters ???

**Comment by leofeyer** [comment]
Maybe we were wrong. I had to remove the test for the `ContaoFramework::validateRequestToken()` method, because I could not mock the `RequestToken` class. Injecting the adapter would solve the problem.

This might be an edge case though, which only applies to the `ContaoFramework` class though.

**Comment by aschempp** [comment]
What was the problem? Your test should mock the ContaoFramework to return a mock adapter (if necessary) ;-)

**Comment by leofeyer** [comment]
How is that supposed to work when testing the `ContaoFramework` class itself? Am I supposed to inject the `ContaoFramework` class into the `ContaoFramework` class???

**Comment by aschempp** [comment]
Hmm, no that won't work. I guess we can't test the request token *inside* the framework class. But we can test the new listener?

**Comment by leofeyer** [comment]
> I guess we can't test the request token inside the framework class.

We could though, if we injected the adapter.

**Comment by aschempp** [comment]
Dunno if I like that idea… guess we should really discuss it

**Comment by leofeyer** [comment]
Thank you.

**Comment by leofeyer** [comment]
I know what we have discussed, but now that I have worked with the new feature and experienced problems, I think it should be all different.

 * We should use `new Adapter()` instead of `$framework->getAdapter()`.
 * We should completely remove the `getAdapter()` and `createInstance()` methods.
 * Instead, we should use `$instance = (new Adapter())->createInstance()` if we need an instance.

This way we would have to inject each adapter separately instead of injecting the framework, which however has the **advantage** that if one of the old classes is replaced, we only have to exchange the adapter with the new service.

**Comment by aschempp** [comment]
> if one of the old classes is replaced, we only have to exchange the adapter with the new service.

why do you mean by that?

**Comment by leofeyer** [comment]
As discussed on Mumble, the current solution with the `ContaoFramework` class being the adapter factory is the best and we want to keep it.

**Comment by leofeyer** [comment]
Merged in 8df561f509efb0e25212bbae37dc475d15c6fc7e.

**Pull request merged**
