### PR TITLE
Fixed wrong quoting in findInSet() database helper

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Comment by leofeyer** [comment]
It should not be necessary to quote the field name unless you are using a reserved keyword.

**Comment by aschempp** [comment]
The docblock is misleading. The *key* is actually the word you're searching for, that's why most of the time a question mark will be supplied as key.

**Comment by leofeyer** [comment]
The key is the column name, not a word you are searching for.

**Comment by Toflar** [comment]
Just see what DC_Table does for eval->csv filters and compare to Contao 3.5 :)

**Comment by leofeyer** [comment]
Merged in 890878c5c39bb6116c20e3f543815185e607ca7e.

**Pull request closed without merging**
