### PR TITLE
Added unit tests for non existent load after definitions and circular re...

### PR DESCRIPTION
**Pull request by Toflar**
...ferences of load after definitions

### CODE REVIEW

**Comment by leofeyer** [comment]
Hm, while applying the CS fixes to your PR I have notices that your `testCircularReference` test is actually wrong. If there are two bundles (e.g. core-bundle and listing-bundle) with the same load-after definition (e.g. integration-bundle), the load-after definition bundle (integration-bundle) has to be loaded **before** the two other bundle and not after them!

**Comment by Toflar** [comment]
Ah, lol - true. Checking!

**Comment by Toflar** [comment]
Ah no, it's correct. The comment might be misleading but the code is correct.

**Comment by leofeyer** [comment]
No way.

```php
// We have 3 bundles so the 3rd must be integration-bundle
$this->assertSame('integration-bundle', $bundlesMapKeys[2]);
```

The integration bundle should be `$bundlesMapKeys[0]`, shouldn't it?

**Comment by leofeyer** [comment]
> Ah no, it's correct. The comment might be misleading but the code is correct.

You are right, the comment is misleading. The test ist just fine.

However, the test seems unnecessary to me, because `testGetBundlesMapForEnvironment()` does test exactly this, too, doesn't it? Maybe we should add the test to the bundles map provider instead?

**Comment by Toflar** [comment]
> However, the test seems unnecessary to me, because testGetBundlesMapForEnvironment() does test exactly this, too, doesn't it? Maybe we should add the test to the bundles map provider instead?

Yeah, obviously it's an additional test - we had 100% coverage before ;)

**Comment by leofeyer** [comment]
Done in 4feed7017dd7ce6e699f685df0bf512c077a155a.

**Pull request merged**
