### PR TITLE
Fixed access to kernel object

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by aschempp** [comment]
Can this be merged?

**Comment by leofeyer** [comment]
Sure, the ticket has already been assigned to the 4.0.0 milestone.

**Comment by aschempp** [comment]
I know. I meant "soon" cause it's stopping my local installation. I guess it's only a click on the merge button? :-P

**Comment by leofeyer** [comment]
Done :)

**Comment by saress** [comment]
Hi Leo,

we have updated 2 different installations from 4.4.20 to 4.4.22 today and the changes in MergeHttpHeadersListener.php cause a "Bad gateway 502" error in the frontend. After replacing the file with the old one, everything works fine again. 

Kind regards,
Saress

**Pull request merged**
