### PR TITLE
[RTM] Add page picker for meta fields in file manager

### PR DESCRIPTION
**Pull request by ausi**
As requested in contao/core#7169

metadata-picker

### CODE REVIEW

**Comment by aschempp** [comment]
Great idea, but are you sure we don't want to keep the existing design and have the icon after the field (by shortening the Link field)?

**Comment by leofeyer** [comment]
I actually like the new design a lot more. We should adjust the other fields as well. 😄

**Comment by ausi** [comment]
> are you sure we don't want to keep the existing design and have the icon after the field (by shortening the Link field)?

This way it was much easier to implement because of the HTML structure of the meta wizard. ☺️

**Comment by leofeyer** [comment]
Changing it everywhere only works for text fields:





It does not work for drop down menus:



So now we can either

a) change the meta wizard only
b) change all text fields
c) leave everything as it is (and adjust the meta wizard).

@contao/developers What do you prefer?

**Comment by Toflar** [comment]
> c) leave everything as it is (and adjust the meta wizard).

**Comment by ausi** [comment]
c

**Comment by aschempp** [comment]
c

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by leofeyer** [comment]
I have tried to implement c) but it looks even worse:



I therefore leave this as is for the moment.

**Comment by frontendschlampe** [comment]
I agree that it looks not perfect, but in this case the functionality is much more important, than the design. It's another point on to do list for backend redesign. ;-)

**Pull request merged**
