### PR TITLE
Use master request to initialize the framework

### PR DESCRIPTION
**Pull request by aschempp**
We should quickly discuss if that's the best option.

### CODE REVIEW

**Comment by leofeyer** [comment]
Let's assume the master request is not one of the Contao routes (so no framework) but triggers a sub-request for one of the Contao routes. Would we want the framework to be initialized with the data of the master request or the current one? How would we want the generated URLs to look like?

**Comment by aschempp** [comment]
Good question. Considering that our Input class does only support the master request, and it was not possible to have subtequests previously, it's probably correct to use master only. 

I'm not really experienced with subrequests though.

**Comment by leofeyer** [comment]
I guess the safest solution would be to initialize the system with the current request. The first request that needs the framework should also have the correct context.

**Comment by Toflar** [comment]
I think the current request is correct. But we can discuss that :)

**Comment by leofeyer** [comment]
The original approach was correct: we have to inject the request stack and work with the current request. @aschempp Do you want to adjust your PR or do you want me to change it?

**Comment by aschempp** [comment]
We haven't discussed the topic…

**Comment by leofeyer** [comment]
Fine, let's wait until Wednesday. Although it is clear what to do :)

**Comment by discordier** [comment]
As I already stated numerous times, always use the current request on the stack.

**Comment by leofeyer** [comment]
So basically @Toflar, @discordier and I all share the same opinion. Shall we still waste time discussing this issue? :)

**Comment by aschempp** [comment]
Yes please…

**Comment by discordier** [comment]
Somewhat related to this.
I just realized that the User class is setting the locale etc. on the current request... this might bear problems when the request is a sub request and others expect it on the master request or vice versa.
The coders would have to reset the user from the DB for every sub request.
I wonder if we can just ignore that until we have a replacement for the legacy authentication layers.

**Comment by leofeyer** [comment]
Ok, we **do** need to discuss this :)

**Comment by leofeyer** [comment]
As discussed on Mumble on May 20th, we want to use the request stack in conjunction with `getCurrentRequest()`.

**Comment by aschempp** [comment]
Is now part of #282

**Comment by leofeyer** [comment]
Fixed in dcc2cf56cc08067ef8dbc854344949d92dcade08.

**Pull request closed without merging**
