### PR TITLE
[RFC] Removed proxy cache killing varying on User-Agent

### PR DESCRIPTION
**Pull request by Toflar**
I guess this goes without any further comment 😄

### CODE REVIEW

**Comment by leofeyer** [comment]
A quick test has shown that the `{{ua::class}}` insert tag is no longer correct without the `Vary` header. Is `$_SERVER['HTTP_USER_AGENT']` set upon ESI requests?

**Comment by leofeyer** [comment]
I actually cannot reproduce the UA problem. I ran some more tests and everything worked as expected. The cache file has this line:

```html
<body id="top" class="<?php echo $this->surrogate->handle($this, '/_fragment?_path=insertTag%3D%257B%257Bua%253A%253Aclass%257D%257D%26_format%3Dhtml%26_locale%3Den%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&_hash=…', '', true) ?>
 start" itemscope itemtype="http://schema.org/WebPage">
```

I double checked that the cached content is loaded and the user agent string was always correct. 🤔

**Comment by aschempp** [comment]
If the request is done by the proxy, how come the user agent can be correct?

**Comment by Toflar** [comment]
> If the request is done by the proxy, how come the user agent can be correct?

Because it's the same?

**Comment by leofeyer** [comment]
But why did you guys get a wrong UA class then during our test this morning?

**Comment by Toflar** [comment]
I'll check that.

**Comment by leofeyer** [comment]
How do we proceed with this one?

**Comment by Toflar** [comment]
Merge as soon as https://github.com/contao/core-bundle/pull/749 is merged.

**Comment by leofeyer** [comment]
Shouldn't it work without #749? The `{{ua::class}}` insert tag is rendered via ESI, so we should not have to vary on the user agent string anymore.

**Comment by Toflar** [comment]
It should, yes.

**Comment by aschempp** [comment]
Except for the mobile layout…

**Pull request merged**
