### PR TITLE
[RFC] Consolidate all front end forms

### PR DESCRIPTION
**Pull request by leofeyer**
This is the PR for https://github.com/contao/core/issues/7292 and https://github.com/contao/core-bundle/pull/247. The goal is to consolidate all front end forms to use the same HTML markup and to remove the "tableless" option.

### CODE REVIEW

**Comment by Toflar** [comment]
Very cool! I just don't see any `form.css` yet :-) But I'm :+1: on this!

**Comment by leofeyer** [comment]
I have changed the status to RFC.

**Comment by aschempp** [comment]
+1 in general. But why are we not using real widgets e.g. In form_login?

**Comment by leofeyer** [comment]
Using real widgets would be the next step. Right now, I don't have the time, so I only changed the backwards incompatible stuff. We can always replace the current solution with real widgets now that the markup is the same.

**Comment by leofeyer** [comment]
Merged in d10c826ae5dd7a4ec984dbe65325cd28ef50abc4.

**Comment by frontendschlampe** [comment]
for first look it feels great - just the submit container in each widget are still in use ;-)

**Comment by leofeyer** [comment]
?

**Comment by leofeyer** [comment]
As quickly discussed on Mumble on May 12th, we also want to skip the "add submit button" option.

**Comment by leofeyer** [comment]
Removed in 5b9d0918341862fb5283719883f29dc2ce809339.

**Comment by frontendschlampe** [comment]
:+1:

**Pull request merged**
