### PR TITLE
[RTM] Use AuthenticationTrustResolver to check for anonymous users

### PR DESCRIPTION
**Pull request by aschempp**
Additional changes for #621

### CODE REVIEW

**Comment by discordier** [comment]
Looks good from my side.

**Comment by aschempp** [comment]
@discordier you can *approve* a PR in GitHub now ;-)

@leofeyer be aware that this is actually a bugfix (and therefore can be merged in 4.3)

**Comment by leofeyer** [comment]
I have set the milestone to 4.3.0, haven't I?

**Comment by aschempp** [comment]
Yeah, but to feature, which cannot be merged at RC stage.

**Comment by leofeyer** [comment]
Merged in c5730d25eb2e4cd4466cf76af45fbcaf7d2b2532.

**Comment by leofeyer** [comment]
Fixed the `services.yml` file in a95e8af6a8683e7bf7668df72239f61803cf926c.

**Pull request merged**
