### PR TITLE
[RFC] Added unit tests for Widget::getPost

### PR DESCRIPTION
**Pull request by aschempp**
Related to https://github.com/contao/core/issues/7855

### CODE REVIEW

**Comment by aschempp** [comment]
We should discuss wether the data result 5 is correct.

**Comment by leofeyer** [comment]
You mean `['foo[k1][0]', 'foo', ['k1'=>'bar'], 'bar'],`? It is not correct IMHO. It should be `['foo[k1][0]', 'foo', ['k1'=>['bar']], 'bar'],` instead.

**Comment by aschempp** [comment]
No, the test is correct. It tests what happens if the requested subkey is not an array. The result is questionable, that's what is currently returned.

**Comment by leofeyer** [comment]
If PHP behaves this way, our class should, too, don't you think?

**Comment by aschempp** [comment]
Well PHP would probably return `b` and not `bar`? Also, if the index would not be numeric it would not return anything (I assume).

**Comment by leofeyer** [comment]
Frankly, I neither see the point of the PR nor do I really understand your problem :)

**Comment by aschempp** [comment]
well, there are two things:

 1. The primary point of the PR was to validate https://github.com/contao/core/issues/7855, to confirm that we do not need the `empty()` check. The code coverage tells us that the array is never empty.

 2. The question is something I noticed while adding test input and adding the actual output. I think it's wrong to return `bar` if the input is `foo => ['k1'=>'bar']` and we're looking for `'foo[k1][0]`

**Comment by leofeyer** [comment]
Ok, then we should fix this when working on contao/core#7855, correct?

**Comment by aschempp** [comment]
I would say so, yes. But I would change that both in 4.0 (and not 3.5)

**Comment by aschempp** [comment]
Please merge this in the develop branch then…

**Comment by aschempp** [comment]
Please don't forget about this

**Comment by leofeyer** [comment]
I won't. I have kept the e-mail in my todo folder.

**Comment by leofeyer** [comment]
Added in b4783ddecbab222c88d53c31658dad5ebe43cc10.

**Pull request closed without merging**
