### PR TITLE
[RTM] Render pretty error screens for the master request and HTML format only

### LINKED ISSUE #298: PrettyErrorScreenListener renders error_404 page but not page_not_found template
There's some strange behavior in the `PrettyErrorScreenListener` class.

If I throw a `PageNotFoundException`, it is converted to a `NotFoundHttpException` by the `ExceptionConverterListener`. The `PrettyErrorScreenListener` will then check that exception.

 - if it is a `NotFoundHttpException`, it will search for a *page_404* type in your page structure and render that

- If there is no *page_404* exception, it will only render the `page_not_found` template if any of the parent exceptions is a `PageNotFoundException`.

That does not really make sense to me. I guess we need to discuss that in an upcoming Mumble call ^^

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #298.

### CODE REVIEW

**Comment by aschempp** [comment]
The event listener should be stateless.

**Comment by leofeyer** [comment]
I have updated the PR accordingly. Is it RTM now?

**Comment by aschempp** [comment]
Maybe you should deprecate the exceptions we're not using anymore?

**Comment by leofeyer** [comment]
We are still using all of the exceptions. We just do not render a pretty error screen for two of them anymore.

**Comment by aschempp** [comment]
Ah, true. Then I think it’s RTM.

I thought about if anyone was using the current Twig templates, but I think we don’t need to keep BC about that.

**Comment by leofeyer** [comment]
Templates != SemVer :)

**Comment by aschempp** [comment]
I know, but it would still break every installation if the templates are gone ;-)

**Comment by leofeyer** [comment]
True. But in this case, I highly doubt that anyone out there already used the templates :)

**Comment by aschempp** [comment]
Agreed

**Comment by Toflar** [comment]
:+1:

**Comment by leofeyer** [comment]
Merged in 552193164633130ca27f6e75f21fcaff9ffd55ad.

**Pull request merged**
