### PR TITLE
[RFC] disallow upload of large images

### PR DESCRIPTION
**Pull request by fritzmg**
Currently Contao uses the system settings `gdMaxImgWidth` and `gdMaxImgHeight` to prevent memory limit errors while processing large images. If an image is larger than any of those values, the image simply will not be processed and shown as is in the front end.

Despite instructing editors not to upload any large images it still happens that they do. This is problematic for the front end - because then you will have large images that a visitor has to download. And the image could break the layout, if the image is expected to be a certain size or aspect ratio.

With this PR you can disallow the back end upload of images larger than the maximum GD size setting.

disallow

This PR depends on fixing the issue of #1506.

### CODE REVIEW

**Comment by aschempp** [comment]
I generally like the idea, however we should not add new options to `tl_settings` as it is kind of deprecated. Such flags should be added to the bundle configuration in my opinion. There already is a `contao.image` configuration namespace.

**Comment by fritzmg** [comment]
Fair enough. What is the general plan with `tl_settings` anyway? People are already complaining that they cannot change certain settings via the system settings in the back end anymore. Will this be done via the Contao Manager in the future? But what's the point of always having to go to the Contao Manager to change certain settings of the Contao installation?

**Comment by aschempp** [comment]
At some point, system configuration and maintenance should all happen in the Manager. Only the Manager is able to configure a non-running Symfony application and rebuild the cache. Also, it's not a task that should be done multiple times, but on initial system setup.

**Comment by fritzmg** [comment]
I have updated PR, using `contao.image.disallow_large_image_upload` now.

**Comment by fritzmg** [comment]
I have renamed the parameter.

Question: should the same apply to front end uploads in the form generator, when enabled? There is already a check like that though - which uses the `imageWidth` and `imageHeight` settings (which is used for automatically resizing the images in the back end upload).

Without any further changes you can achieve the same effect in the front end by setting the `imageWidth` and `gdMaxImgWidth` and `imageHeight` and `gdMaxImgHeight` respectively to the same value.

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
