### PR TITLE
[RFC] Followup #755 Extended picker

### PR DESCRIPTION
**Pull request by ausi**
This adresses the issue discussed in https://github.com/contao/core-bundle/pull/755#issuecomment-294716212

### CODE REVIEW

**Comment by leofeyer** [comment]
The changes have been added in 896a5f90cbee7051c9ee76e9add52820393acff2.

**Comment by Toflar** [comment]
The `core.js` change is missing.

**Comment by ausi** [comment]
The change in the `core.js` is not needed in leo’s version I think, because the ID and field name switched the order.

**Comment by Toflar** [comment]
Ah, ok.

**Pull request closed without merging**
