### PR TITLE
[RTM] Use the Doctrine cache to store the latest version

### PR DESCRIPTION
**Pull request by leofeyer**
This PR is an enhancement to #442.

### CODE REVIEW

**Comment by aschempp** [comment]
We don't need the cache bundle, we just need the library

**Comment by leofeyer** [comment]
As discussed, we need the bundle to have the console commands available. E.g.

```
app/console doctrine:cache:clear contao.cache
```

**Comment by leofeyer** [comment]
Merged in aa5449a1becabc3bf7eb545edb4c4ed8e26b9625 then.

**Comment by discordier** [comment]
> As discussed, we need the bundle to have the console commands available. E.g.

This does belong to the application then, not the bundle, the bundle does not need nor know about the commands of another bundle.

**Comment by leofeyer** [comment]
It is a bit strange if the bundle suggest running a console command and at the same time does not require the bundle providing the command, isn't it?

**Comment by discordier** [comment]
Not really, I mean for these occasions there exists a complete "suggests" section in the `composer.json`.
I suggest you do something but I do not require you to do it. You can still simply remove the cache dir by hand if you want to completely omitting the "bloat" of the bundle which might cause conflicts with another bundle or package.

You should require stuff you use classes from and suggest packages that bring more user experience etc.

**Comment by aschempp** [comment]
As suggested in Slack, I think we should actually put a link to the manual, which can describe the available options in-depth.

**Comment by leofeyer** [comment]
@discordier's argument is about the Composer requirement.

**Comment by discordier** [comment]
Exactly, but now I wonder to which "options" @aschempp is referring to.

**Pull request merged**
