### PR TITLE
Use the decoded URL in the search results

### PR DESCRIPTION
**Pull request by ausi**
See #1085

### CODE REVIEW

**Comment by leofeyer** [comment]
We should probably change this in https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/ModuleSearch.php#L258-L260, don't you think?

**Comment by ausi** [comment]
I don’t think so. If someone currently uses `$this->url` for the `href` attribute, it could lead to problems if we change the values in the module.

**Comment by leofeyer** [comment]
I only want to change `$this->url` not `$this->href`. If someone used `$this->url` for the `href=""` attribute, they made a mistake.

**Comment by ausi** [comment]
Makes sense. Should be OK then to change `$this->url` instead of modifying the template...

**Comment by leofeyer** [comment]
Fixed in 89116b26de2b6dfc95629035aa2aa62050ca8d59.

**Comment by ausi** [comment]
Shouldn’t we use 

```php
$objTemplate->url = \StringUtil::specialchars(urldecode($arrResult[$i]['url']), true, true)
```

?

**Comment by leofeyer** [comment]
Why?

**Comment by ausi** [comment]
Because the URL may include special characters (after urldecoding it) that have to be escaped for HTML.

**Comment by leofeyer** [comment]
Fixed in 6e157e160a1f2c9ab2cae165c538c9fb73b0269d.

**Pull request closed without merging**
