### PR TITLE
Tests for contao/core#7882

### PR DESCRIPTION
**Pull request by ausi**
See contao/core#7882

### CODE REVIEW

**Comment by leofeyer** [comment]
@ausi The tests fail on my system. Can you please fix them?

```
PHPUnit 4.8.6 by Sebastian Bergmann and contributors.

...............................................................  63 / 158 ( 39%)
...............F..E.....F.FFFF.F............................... 126 / 158 ( 79%)
................................

Time: 6.22 seconds, Memory: 9.00Mb

There was 1 error:

1) Contao\CoreBundle\Test\Contao\ImageTest::testExecuteResizeSvgWithoutViewBoxAndDimensions
Division by zero

~/standard-edition/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Image.php:699
~/standard-edition/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Image.php:573
~/standard-edition/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Image.php:506
~/standard-edition/vendor/contao/core-bundle/tests/Contao/ImageTest.php:1400

--

There were 7 failures:

1) Contao\CoreBundle\Test\Contao\ImageTest::testExecuteResizeSvgPercentageDimensions
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'-50'
+'0'

~/standard-edition/vendor/contao/core-bundle/tests/Contao/ImageTest.php:1300

2) Contao\CoreBundle\Test\Contao\ImageTest::testGetPixelValue with data set "ex" ('2ex', 16)
Failed asserting that 0 is identical to 16.

~/standard-edition/vendor/contao/core-bundle/tests/Contao/ImageTest.php:1493

3) Contao\CoreBundle\Test\Contao\ImageTest::testGetPixelValue with data set "pc" ('1pc', 16)
Failed asserting that 0 is identical to 16.

~/standard-edition/vendor/contao/core-bundle/tests/Contao/ImageTest.php:1493

4) Contao\CoreBundle\Test\Contao\ImageTest::testGetPixelValue with data set "in" ('0.16666666666667in', 16)
Failed asserting that 0 is identical to 16.

~/standard-edition/vendor/contao/core-bundle/tests/Contao/ImageTest.php:1493

5) Contao\CoreBundle\Test\Contao\ImageTest::testGetPixelValue with data set "cm" ('0.42333333333333cm', 16)
Failed asserting that 0 is identical to 16.

~/standard-edition/vendor/contao/core-bundle/tests/Contao/ImageTest.php:1493

6) Contao\CoreBundle\Test\Contao\ImageTest::testGetPixelValue with data set "mm" ('4.2333333333333mm', 16)
Failed asserting that 0 is identical to 16.

~/standard-edition/vendor/contao/core-bundle/tests/Contao/ImageTest.php:1493

7) Contao\CoreBundle\Test\Contao\ImageTest::testGetPixelValuePercentageDeprecated
Failed asserting that exception of type "PHPUnit_Framework_Error_Deprecated" is thrown.

FAILURES!
Tests: 158, Assertions: 434, Errors: 1, Failures: 7.
```

**Comment by ausi** [comment]
The tests are for new code added in contao/core#7882 which should be merged first.

**Comment by leofeyer** [comment]
Geez! My bad :(

**Comment by leofeyer** [comment]
Merged in 9d098411a6795587294e0746cbd79c504f5a346c.

**Pull request closed without merging**
