### PR TITLE
[RTM] Unify customTpl handling (see #235)

### PR DESCRIPTION
**Pull request by leofeyer**
This is the PR regarding #235.

 - [x] `ContentHyperlink`: the template is set dynamically depending on the `useImage` field.
 - [x] `ModuleEventMenu`: the template is set dynamically depending on the `cal_format` field.
 - [x] `ModuleLogin`: the template is set dynamically depending on the `cols` field and on the login status.
 - [x] `ModuleSearch`: the template is set dynamically depending on the `searchType` field.
 - [x] `ModuleNewsMenu`: the template is set dynamically depending on the `news_format` field.

### CODE REVIEW

**Comment by leofeyer** [comment]
I have consolidated all core templates now and changed the status to RFC. There is now one `mod_login` template, one `mod_search` template and one `ce_hyperlink` template.

The "tableless" option is still available, it seems that it has nothing to do with the consolidation and therefore should be a separate PR.

@contao/developers Please review and comment.

**Comment by Toflar** [comment]
Looks good to me :+1: The only remark: The update hint should also include a hint that the module and content element type is now considered in the template group and might thus require adjustments by the developer.

**Comment by leofeyer** [comment]
Added in 14273509b8c061a25d406719a19207fb5bbc5c2e. The PR is RTM to me now.

**Comment by Toflar** [comment]
Excellent. I'm +1 on this.

**Comment by leofeyer** [comment]
There is now a PR which deals with removing the "tableless" option: https://github.com/contao/core-bundle/pull/249

**Comment by leofeyer** [comment]
The "tableless" option has been removed in d10c826ae5dd7a4ec984dbe65325cd28ef50abc4.

**Pull request merged**
