### PR TITLE
[WIP] Added options to configure YouTube embedding

### PR DESCRIPTION
**Pull request by aschempp**
Probably needs a database migration too to set the default options on update.

### CODE REVIEW

**Comment by leofeyer** [comment]
Wouldn't it be much easier if you reversed the logic?

 * Hide suggested videos when the video finishes
 * Hide player controls
 * Hide video title and player actions

That would be backwards compatible and does not require any migration.

**Comment by aschempp** [comment]
The options are taken straight from youtube…

**Comment by fritzmg** [comment]
In my extension ([fritzmg/contao-youtube-iframe](https://github.com/fritzmg/contao-youtube-iframe/)) I also designed the checkboxes this way so that if you check none of them, the default values of YouTube are active. Currently I support:

* Show closed captions by default (`cc_load_policy=1`)
* White progress bar (`color=white`)
* Disallow fullscreen (`fs=0`)
* Disable annotations by default (`iv_load_policy=3`)
* Modest branding (`modestbranding=1`)
* Disable related videos (`rel=0`)
* Disable information (`showinfo=0`)

**Comment by leofeyer** [comment]
If @fritzmg has already made an extension, there is no reason to merge this PR, is there?

**Comment by fritzmg** [comment]
I think it would make sense to provide such functionality in the core.

**Comment by leofeyer** [comment]
Ok, then @aschempp please update the PR and reverse the logic as discussed above.

**Comment by aschempp** [comment]
I wonder if we should merge @fritzmg's features instead, apparently there are way more options than my PR provides?

**Comment by leofeyer** [comment]
Implemented in c7b4f387ea111871e05e9d704b0626ceefc5d2e9.

**Pull request closed without merging**
