### PR TITLE
[RFC] Feature/articletree widget

### PR DESCRIPTION
**Pull request by agoat**
This PR adds an article tree widget as suggested in #747. It allows selecting articles the same way as pages with the new dca picker (for the content elements `Article` and `Article teaser`).

It depends on the PR #906. Otherwise no articles can be selected.

### CODE REVIEW

**Comment by agoat** [comment]
It looks like I have to rework this PR as there will be a lot of changes to the dcaPicker introduced in the next bugfix release.

**Comment by leofeyer** [comment]
> as there will be a lot of changes to the dcaPicker introduced in the next bugfix release

Probably only in the next minor version (Contao 4.5).

**Comment by agoat** [comment]
As the dca picker will be rewritten (#950), I will wait for the new implementation and adjust this PR accordingly.

**Comment by agoat** [comment]
I close this in favour for #999.

**Pull request closed without merging**
