### PR TITLE
Fixed missing initialization of the framework

### PR DESCRIPTION
**Pull request by Toflar**
Otherwise page types are not found.

### CODE REVIEW

**Comment by leofeyer** [comment]
The you can remove the call in line 304 (now 306) I guess.

**Comment by aschempp** [comment]
This looks like it will boot the framework in all cases, even unnecessarily, like when rendering a service unavailable exception?

**Comment by Toflar** [comment]
Yeah basically it was just a quickfix instead of a issue-only so that it can be fixed properly including tests. I just can't handle so many branches atm so please just fix accordingly :D

**Comment by leofeyer** [comment]
Ok, will do.

**Comment by leofeyer** [comment]
Fixed in 682b5b8c1b2c470031097bdfb3d931aaf8f4b169.

**Pull request closed without merging**
