### PR TITLE
[RTM] Added the insert tag flag for absolute URLs

### PR DESCRIPTION
**Pull request by qzminski**
Works like this: `{{link_url::123|absolute}}`.

### CODE REVIEW

**Comment by qzminski** [comment]
Will certainly do if this is merged.

**Comment by leofeyer** [comment]
This does not really work, does it? The insert tag is cached, so if someone has both `{{link_url::123|absolute}}` and `{{link_url::123}}`, they will always get the absolute URL (second call returns the cached value).

**Comment by qzminski** [comment]
Well, the `$strTag` is cached which is the insert tag and the flag, so they are both different tags in fact. It seems to work fine for me. Or am I missing something?

**Comment by leofeyer** [comment]
No, you are right. My bad.

**Comment by leofeyer** [comment]
Thank you @qzminski.

**Pull request merged**
