### PR TITLE
[RTM] Insecure document root is allowed for localhost

### PR DESCRIPTION
**Pull request by aschempp**
see #67 

/cc @dtomasi

### CODE REVIEW

**Comment by Toflar** [comment]
Tests are missing :)

**Comment by aschempp** [comment]
I have updated the code to check the IP instead of host to allow for IPv6.

@Toflar it's currently using `die_nicely` so tests would be hard ;-)

**Comment by dtomasi** [comment]
+1

Thanks! That´s also fine for me!

**Comment by Toflar** [comment]
> @Toflar it's currently using die_nicely so tests would be hard ;-)

Then we need to add a  `FIXME` :)

**Comment by aschempp** [comment]
Agreed, `FIXME` added.

**Pull request merged**
