### PR TITLE
[WIP] No more magic

### PR DESCRIPTION
**Pull request by leofeyer**
This is the PR to contao/symfony-todo#5 as discussed on Mumble yesterday.

### CODE REVIEW

**Comment by leofeyer** [comment]
So, I'm ready to merge now. Here's what I've changed:

 * Register all bundles in the app kernel instead of the `autoload.json` file
 * Use annotations to define routes in the controller classes
 * Remove the prepend stuff and configure everything in `app/config`

The next step would be to add the bundle sorter and to remove the Contao kernel, but I cannot do this until we have merged @aschempp's [Contao resources from DIC](https://github.com/contao/core-bundle/pull/55) pull request.

The corresponding PR for the standard edition is here: https://github.com/contao/standard-edition/pull/1

@contao/developers Please review and vote.

# Structural changes

There have also been some structural changes regarding the git repos:

 * `contao/contao` is now a meta package, which includes the default Contao bundles and the Contao components. It's purpose is to add Contao to an existing Symfony application (see the [installation guide](https://github.com/contao/contao)).

 * `contao/standard-edition` is the successor of `contao/contao` and includes a custom Symfony standard edition ready for Contao. The [README file](https://github.com/contao/standard-edition/tree/feature/no-more-magic) has been adjusted accordingly.

**Comment by aschempp** [comment]
Why has this been merged without any feedback?

**Comment by aschempp** [comment]
http://symfony.com/doc/current/contributing/code/core_team.html#pull-request-merging-policy

**Comment by leofeyer** [comment]
We have discussed it on Mumble and you have asked me to make it a feature branch so there is a single commit on the `develop` branch which we can revert if necessary. I have explicitly asked you if I can then merge it without having to wait for feedback, because I won't make any progress if I have to wait several days for feedback.

If there is no feedback at all, what am I supposed to do?

**Comment by Toflar** [comment]
You did that PR yesterday, 15:18! How are we supposed to answer within that short period of time, please?

**Comment by leofeyer** [comment]
> We have discussed it on Mumble and you have asked me to make it a feature branch so there is a single commit on the `develop` branch which we can revert if necessary. I have **explicitly asked you** if I can **then merge it without having to wait for feedback**

**Pull request merged**
