### PR TITLE
install.php not working

### PR DESCRIPTION
**Pull request by xchs**
This adds the new/old route to the Contao install tool.

### CODE REVIEW

**Comment by aschempp** [comment]
This should be merged into `develop` afaik, in 4.3 the `install.php` is still necessary.

**Comment by leofeyer** [comment]
No, it is not (at least not in the standard edition). And using the `install.php` entry point is currently broken in Contao 4.3, so `/contao/install` is in fact the only way to install Contao 4.3.

**Comment by aschempp** [comment]
As far as I know it is not necessary in the managed edition, but it is in the standard edition…

**Comment by leofeyer** [comment]
Not if you install the standard edition via Composer, which I guess is what everyone using the standard edition does.

**Comment by xchs** [comment]
> As far as I know it is not necessary in the managed edition

I'm using the ME and it IS actually necessary to open the Contao install tool via `/contao/install`. Otherwise you get an error.

**Comment by aschempp** [comment]
install.php not working is a bug that should be fixed.

**Comment by leofeyer** [comment]
Feel free to create a PR if you really thing that it is important – because I don't.

**Comment by fritzmg** [comment]
This generates quite some confusion in the forum currently, since people are of course trying to open `/install.php` and do not know about the `/contao/install` route.

**Comment by aschempp** [comment]
https://github.com/contao/manager-bundle/commit/4d2babb216341cf46c8146fc50730028af6e8275 is probably the best solution, maybe that should be merged in the next hotfix instead of develop @leofeyer ?

**Comment by leofeyer** [comment]
@aschempp You can merge it in whatever branch you want. 😄

**Comment by m-vo** [comment]
Btw.: the hint on the 'incomplete installation' error screen still points the user to ``/install.php``. Might be better to change it to ``/contao/install``.

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/languages/en/exception.xlf#L51

**Comment by xchs** [comment]
> Btw.: the hint on the 'incomplete installation' error screen still points the user to /install.php. Might be better to change it to /contao/install.

This is exactly what this PR was made for.

**Comment by aschempp** [comment]
Added in 4.3.10: https://github.com/contao/manager-bundle/commit/d8c9389ab5e6b0994634baddccc7bba519ff1857

**Comment by leofeyer** [comment]
See https://github.com/contao/managed-edition/issues/7.

**Pull request merged**
