### PR TITLE
[RTM] increase imageWidth/Height default

### PR DESCRIPTION
**Pull request by fritzmg**
The old defaults for the `imageWidth` and `imageHeight` setting seem a bit low to me, especially in these modern times, with responsive images and high DPI display devices.

I recently forgot to change these values and now a customer needs to re-upload all pictures again, since they all got automatically downscaled to 800x600 -_-

Not sure what the new defaults should be though. 1280? 1680? 1920?

### CODE REVIEW

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by aschempp** [comment]
Well the default value is not based on "usefulness" but on memory limits, right?

**Comment by fritzmg** [comment]
> Well the default value is not based on "usefulness" but on memory limits, right?

You are probably thinking of the `gdMaxImgWidth` and `gdMaxImgHeight` setting, which is currently set to `3000` for both by default.

**Comment by Aybee** [comment]
True, I have not even noticed, as I always upload with FTP.

Maybe the default setting should have no restriction.

gdMax... should take care of memory limits.

**Comment by ausi** [comment]
> Maybe the default setting should have no restriction.

I agree, the default for `imageWidth` and `imageHeight` should be changed to `0`.

**Comment by fritzmg** [comment]
Setting `imageWidth` and `imageHeight` to zero by default was not the solution unfortunately. This causes any front end uploads to not work anymore. You will get the following error message in the front end:
```
Die Datei … übersteigt die maximale Bildbreite von 0 Pixel!
```

**Comment by ausi** [comment]
I think this is another bug then in https://github.com/contao/core-bundle/blob/133cebc0a9716f935637dcb64cd46a5b37920d02/src/Resources/contao/forms/FormFileUpload.php#L177 and https://github.com/contao/core-bundle/blob/133cebc0a9716f935637dcb64cd46a5b37920d02/src/Resources/contao/forms/FormFileUpload.php#L186

**Pull request merged**
