### PR TITLE
[RTM] Allow sub-subpalettes in DC_Table

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by leofeyer** [comment]
I like it. It does not yet support "edit all". Are you going to complete it?

**Comment by leofeyer** [comment]
Are you? :smile:

**Comment by aschempp** [comment]
You can assign it to me, but idk when I'll find the time…

**Comment by leofeyer** [comment]
It should be no more than 10 minutes work, you have told me :smile:

**Comment by leofeyer** [comment]
There is also a bug in the implementation. If the inner palette is closed, the outer one can be opened and closed as usual. However, if the inner palette is open and the outer one is closed, the outer palette is not loaded correctly when opened again (page reload required).

See https://www.dropbox.com/s/z0hrq5k1kcv9tig/contao-palettes.mov?dl=0

**Comment by aschempp** [comment]
I have fixed the issue 😎

**Comment by leofeyer** [comment]
So is the pull request RTM now?

**Comment by aschempp** [comment]
It worked in all cases I tested. But please someone else test it :D

**Comment by Toflar** [comment]
Is there any place where it might be useful in the core bundle itself?

**Comment by leofeyer** [comment]
Probably yes. I needed it once but then implemented a workaround. Don't remember though.

**Comment by aschempp** [comment]
This should be tagged for 4.2 again, right?

**Comment by leofeyer** [comment]
Merged in ca2b1ce43f310b8df56a7f2c407a1b87458eda4f.

**Pull request merged**
