### PR TITLE
[RTM] Set all defaults in the Configuration class

### PR DESCRIPTION
**Pull request by leofeyer**
This is the follow up PR for #660.

### CODE REVIEW

**Comment by aschempp** [comment]
This does not work, see http://symfony.com/doc/current/configuration/using_parameters_in_dic.html

**Comment by leofeyer** [comment]
You are right, it does not work for anything but strings, so it does not work for `prepend_locale` but it will work for `encryption_key`.

**Comment by leofeyer** [comment]
So what do we do now? Shall I change this PR accordingly or do you want to rework #660?

**Comment by aschempp** [comment]
You're right, I misunderstood the manual that it would result in a string value instead of the parameters. I would simply just change the `kernel.secret` and keep `prepend_locale` as-is, also because it would be a potential config break.

**Comment by leofeyer** [comment]
I would prefer to have all the default configuration in the `Configuration` class, so we do not need a `contao:` section in the `config.yml` file at all.

**Comment by aschempp** [comment]
We cannot rely on a global parameter for our configuration, as it would imply it to be set in the `parameters.yml`. Same goes with `kernel.secret`, it does not default to `secret` but that's a setup of the application.

**Comment by leofeyer** [comment]
Then just do `$container->hasParameter('prepend_locale') ? $container->getParameter('prepend_locale') : false`.

**Comment by aschempp** [comment]
That would still be "assuming application configuration".

**Comment by SGehle** [comment]
Why is the pid get-parameter ignored?

**Pull request closed without merging**
