### PR TITLE
remove frameborder attribute from media iframes

### PR DESCRIPTION
**Pull request by fritzmg**
Having `frameborder="0"` on iframes produces the following validation error:
```
The frameborder attribute on the iframe element is obsolete. Use CSS instead.
```
See https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.contao.org%2Fen%2Fmedia-elements.html

_Note:_ there are a few places in the back end where `frameborder="0"` is used on iframes as well (`be_preview.html5`, `core.js`). Those are not changed with this PR.

### CODE REVIEW

**Comment by leofeyer** [comment]
The problem is that it does not render properly without the attribute. And that's more important than the validator.

**Comment by ausi** [comment]
Then `frameborder="0"` should probably be replaced with `style="border:0"`.

**Comment by fritzmg** [comment]
> Then frameborder="0" should probably be replaced with style="border:0".

But you also don't add `style="margin:0"` for every `<figure>` for example. Why should it be done for `<iframe>`?

**Comment by ausi** [comment]
You are right @fritzmg. The reset.css is the better place for that.

**Comment by leofeyer** [comment]
It's not about `border: 0`. I recall that some browsers – presumably IE6 to IE? – always rendered the iframe border without the attribute.

**Comment by fritzmg** [comment]
I see. But hasn't the minimum IE version for the Contao CSS framework been raised to IE 8 anyway?

**Comment by leofeyer** [comment]
Probably even IE11 meanwhile. Can you do a quick test which browsers might be affected?

**Comment by fritzmg** [comment]
Not really :grin: I can only test IE11 (and EDGE). I don't have the facilities (VMs) to test older IE versions right now (since we do not support anything lower than IE11 either).

IE11 definitely has no problem with
```css
iframe {
    border: 0;
}
```

**Comment by ausi** [comment]
I can do the test.

**Comment by ausi** [comment]
Works in IE9+  
Doesn’t work in IE8-

**Comment by leofeyer** [comment]
Thank you @ausi. I guess we can drop the attribute then.

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
