### PR TITLE
[RFC] Fix the Symfony version display in the debug bar

### PR DESCRIPTION
**Pull request by leofeyer**
This PR fixes the Symfony version display in the debug bar. It will colorize the output depending on whether the Symfony version has known issues and this does not work if we inject the Contao version.

Also, it is wrong to inject the Contao version, because the end product is a Symfony app (as stated in the keynote). Contao is "just" a bundle and therefore should have the version number attached to its icon (see the screenshot above).

### CODE REVIEW

**Comment by aschempp** [comment]
I agree with removing it from Symfony app. But I would prefer to show the container state as previously. The Contao version is available from the popup.

**Comment by leofeyer** [comment]
So is the container scope :)

**Comment by aschempp** [comment]
True. We should only add the most relevant information… Not sure what that would be though.

**Comment by leofeyer** [comment]
I'd say the version number. People usually know whether they are in the back end or in the front end :)

**Comment by aschempp** [comment]
Yeah, they usually also know the Contao version (which is visible in the backend) :-P

**Comment by leofeyer** [comment]
True. Then just add no `sf-toolbar-info-piece-additional` at all?

**Comment by aschempp** [comment]
Except if we can mimic the "is supported" information from Symfony…

**Comment by leofeyer** [comment]
We'd have to find out how they check the version; they are probably using the [Security Advisories checker API](https://security.sensiolabs.org/api).

**Comment by bytehead** [comment]
@leofeyer we did this already for contao < 4: [contao security advisories](https://github.com/1up-lab/contao-security-advisories). It also checks the installed extensions (by the composer-client) against the security lists. I would like to have a security check shipped with the core bundle. At least usable with a cli command.

**Comment by aschempp** [comment]
Great idea, but probably for 4.1 (as 4.0 is RC)?

**Comment by leofeyer** [comment]
I'll change the milestone after I have merged the fixes.

**Pull request merged**
