### PR TITLE
[RFC] Updated installation documentation

### PR DESCRIPTION
**Pull request by bytehead**
See discussions/questions in https://github.com/contao/core-bundle/issues/1364 and https://github.com/contao/core-bundle/issues/1366.

### CODE REVIEW

**Comment by fritzmg** [comment]
I think a description on how to update the database without the Contao Install Tool (installation-bundle) would be nice too :)

**Comment by leofeyer** [comment]
@bytehead I would prefer it the other way round. Recommend all three by default and add notes that another client implementation can be used and that the install tool can be omitted (sometime in the future).

Do you want me to change the text accordingly?

**Comment by bytehead** [comment]
👍

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
