### PR TITLE
[RFC] Use try-finally blocks to close all opened output buffers

### PR DESCRIPTION
**Pull request by ausi**
As discussed in https://github.com/contao/core-bundle/pull/698#issuecomment-279708701

@antoinedavid can you verify that this solves your issue with `sendToBrowser()`?

### CODE REVIEW

**Comment by Toflar** [comment]
Excellent work @ausi, thanks!

**Comment by aschempp** [comment]
Why not simply use `ob_get_clean()`?

**Comment by ausi** [comment]
> Why not simply use `ob_get_clean()`?

What do you mean by that? In the finally block we only want to close the output buffer, the contents of the buffer are not needed there.

**Comment by aschempp** [comment]
Nevermind. Instead of `ob_get_content()` and `finally` we could have used `ob_get_clean()` and `catch`. But does not really make a difference I guess :-)

**Pull request merged**
