### PR TITLE
[RFC] Add redirect route for the contao backend

### PR DESCRIPTION
**Pull request by bytehead**
See #186

### CODE REVIEW

**Comment by leofeyer** [comment]
I think we should add the redirect route in the `app/config/routing.yml` file instead of creating a controller method, which does nothing. This is also recommended here:

http://symfony.com/doc/current/cookbook/routing/redirect_in_config.html

**Comment by bytehead** [comment]
Makes sense to me. But that would be in contao/standard-edition? I already have some working code.

**Comment by leofeyer** [comment]
>  But that would be in contao/standard-edition?

Exactly. You don't have to create another PR though. I could just port your suggestion.

**Comment by bytehead** [comment]
I added this before the `ContaoCoreBundle:` in `app/config/routing.yml`:

```yml
contao_backend_alias:
    path: /contao
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: contao_backend
        permanent: true
        _scope: backend

```

**Comment by leofeyer** [comment]
I committed it on your behalf in contao/standard-edition@ff9df8671eb8c026611bba1b4f33b4e56e20dd37 and 3a4319326e80f86eb92131f4eb99880108d6d8d9.

**Comment by bytehead** [comment]
Thanks! And cleaner that way (from `/contao/` to `/contao`). :+1:

**Pull request closed without merging**
