### PR TITLE
Always enable twig bundle, but only load config if bundle is available

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by discordier** [comment]
How come the service kernel.bundles get's retrieved in here but is not available?
Didn't you say in Ahrweiler that it is present?

**Comment by aschempp** [comment]
Not sure what you mean. `kernel.bundles` is an array with key="bundle name" and value="bundle class". I explained that the bundle instances are not available.

**Comment by aschempp** [comment]
If you are referring to the unit tests: I don't know. They are set in the kernel:
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/Kernel.php#L579

**Comment by leofeyer** [comment]
Do we really need to wrap all the calls in `if` conditions? We are loading the bundles in the `autoload.json` file, so we can safely assume that the bundles are available, can't we?

**Comment by aschempp** [comment]
It's similar to what Symfony does: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L77

The `autoload.json` does not make sure the bundles are loaded, it just loads them if they are there.

**Comment by leofeyer** [comment]
> The `autoload.json` does not make sure the bundles are loaded

That's true, but Composer ensures that the bundles are there, so they are always loaded :)

**Comment by aschempp** [comment]
I still think its good practice, otherwise the container building will fail, and even our custom error messages wont be rendered.

**Comment by leofeyer** [comment]
Can you please update/rebase this PR so it handles the `security.yml` file? Then I should be able to merge it.

**Comment by aschempp** [comment]
Done, including some fixes.

**Comment by leofeyer** [comment]
How about renaming `prependBundleConfig()` to `prependConfigIfLoaded()`?

**Comment by aschempp** [comment]
hmm, then it should be `prependConfigIfBundleIsLoaded`? :D
Because it's about the given bundle…

**Comment by leofeyer** [comment]
Not quite, because the first argument would be the bundle name:

```php
$this->prependConfigIfLoaded('DoctrineBundle', 'doctrine.yml', $container);
```

But we might as well use `prepareBundleConfig()`.

**Comment by Toflar** [comment]
To me it looks good as it is now. The method is well documented saying "if loaded" and honestly, `prependConfigIfLoaded` looks a bit awkward :D

**Comment by leofeyer** [comment]
Another thing: We are now always loading the web profiler, aren't we? Previously we only loaded it in the `dev` and `test` environments (whereby `test` does not make sense at all).

**Comment by aschempp** [comment]
No, we're only loading it if the bundle is there. And the bundle is only there in `dev`/`test` according to autoload.json.

**Comment by leofeyer** [comment]
I see (now).

**Pull request merged**
