### PR TITLE
[RTM] fix DropZone showing HTML in errors

### LINKED ISSUE #1506: DropZone cannot handle errors
If `$this->blnHasError` is set to true for `Contao\DropZone` during `uploadTo(…)` for example, there will simply be a `500` response and the error will not be visible in the DropZone. Instead it will show the following:

dropzone-error

In this example I simulated a file with an invalid file name that would trigger
```php
// Invalid file name
if (!\Validator::isValidFileName($file['name']))
{
	\Message::addError($GLOBALS['TL_LANG']['ERR']['filename']);
	$this->blnHasError = true;
}
```
within `FileUpload::uploadTo`. This can be fixed by adding
```diff
	// Redirect or reload
	if (!$objUploader->hasError())
	{
		if ($blnIsAjax)
		{
			throw new ResponseException(new Response(\Message::generateUnwrapped(), 201));
		}

		// Do not purge the html folder (see #2898)
		if (isset($_POST['uploadNback']) && !$objUploader->hasResized())
		{
			\Message::reset();
			$this->redirect($this->getReferer());
		}

		$this->reload();
	}
+	elseif ($blnIsAjax)
+	{
+		throw new ResponseException(new Response(\Message::generateUnwrapped(), 500));
+	}
```
in `DC_Folder::move`. However, then it will still look like this:

dropzone-error-2

Since the `Message` class automatically wraps the messages with HTML and DropZone expects the server response to be pure text.

### PR DESCRIPTION
**Pull request by fritzmg**
This fixes #1506. Not the most elegant solution though. Fix is needed for #1507.

### CODE REVIEW

**Comment by xchs** [comment]
@fritzmg The PR should be targeted against the [4.4 branch](https://github.com/contao/core-bundle/tree/4.4), shouldn't it?

**Comment by fritzmg** [comment]
Hm, true, I mis-targeted because I have done this for a new feature.

**Comment by fritzmg** [comment]
I forcefully changed the base now... not sure if that was a good idea ;)

**Comment by leofeyer** [comment]
Wouldn't a simple `strip_tags()` do the job, too?

**Comment by fritzmg** [comment]
Well, the `ResponseException` is thrown in `DC_Folder`, however there I have no information about whether the response is for the DropZone or not. Unless we can assume that any AJAX Request wants the messages from the response in pure text instead of HTML?

**Comment by leofeyer** [comment]
> Unless we can assume that any AJAX Request wants the messages from the response in pure text instead of HTML?

I guess we can safely assume this. 😉

**Comment by fritzmg** [comment]
@leofeyer this needs to be merged too - otherwise #1507 won't work properly :)

**Comment by leofeyer** [comment]
Since you did not like the `strip_tags()` approach, I have implemented something else in 8c99c38fdd5b435037ee546b26abe6f4fefd916d. Do you like it?

**Comment by leofeyer** [comment]
I have backported the changes in a53201e0cbd96c177495b92fca298a4b75154ded.

**Pull request closed without merging**
