### PR TITLE
[RFC] Store the full URI in the search results

### PR DESCRIPTION
**Pull request by leofeyer**
This is the follow-up PR to contao/core#8331.

@fritzmg Does it solve your issue?

@Toflar Is `varchar(255)` long enough to store the full URI?

### CODE REVIEW

**Comment by Toflar** [comment]
Hard to say if 255 are enough. But imho that question is the same if it's a relative URL :D Most domains are not 250 characters long ;)

**Comment by Toflar** [comment]
I'd leave it as is for now.

**Comment by leofeyer** [comment]
Merged in 3d03fe0bf2f894fa992470229e4649f177945c49. I have also patched contao.org to use absolute URLs and it seems to work like a charm.

**Comment by Toflar** [comment]
That's a bugfix then. Should be backported to 3.5.

**Comment by leofeyer** [comment]
Yes. Will do if no problems occur.

**Comment by fritzmg** [comment]
> @fritzmg Does it solve your issue?

I can only test with Contao 3.5 right now, but if it's the same as doing
```php
'url' => \Environment::get('uri')
```
in [/system/modules/core/classes/FrontendTemplate.php#L321](https://github.com/contao/core/blob/3.5.12/system/modules/core/classes/FrontendTemplate.php#L321), then yes, it should work.

**Comment by leofeyer** [comment]
Yes, that is the same. In Contao 4, `get('uri')` will include the script name though (e.g. `app_dev.php`) and `get('relativeRequest')` will not, that's why I have used the latter.

**Comment by leofeyer** [comment]
Back ported in 3e6dc79e8914b714878f3a76ec882fb6c7338b7e.

**Pull request merged**
