### PR TITLE
PHP7 compatibility

### PR DESCRIPTION
**Pull request by leofeyer**
See http://php.net/manual/en/migration70.incompatible.php

### CODE REVIEW

**Comment by leofeyer** [comment]
Take the following example:

```php
System::importStatic($callback[0])->$callback[1]();
```

We have to options to fix this:

```php
// Requires PHP 5.5+ (Contao 4.1)
System::importStatic($callback[0])->($callback[1])();

// Compatible with PHP 5.4+ (Contao 3.5)
System::importStatic($callback[0])->{$callback[1]}();
```

In Contao 4.1, we could use the new syntax. However, I don't know if we care about PHP7 compatibility for Contao 3.5?

**Comment by discordier** [comment]
PHP 5.6 Support timeline: Support until 28 Aug 2016 (security 28 Aug 2017)
Contao 3.5 Support timeline: 01 Jun 2018 (security 01 Jun 2019)

So yes, we must support PHP7 for Contao 3.5

**Comment by leofeyer** [comment]
:+1:

**Comment by leofeyer** [comment]
PHP7 support for Contao 3.5 has been added in contao/core@5cc52edd9291784907ba1806101bb95f6ef253dc.

**Pull request closed without merging**
