### PR TITLE
[RFC] Add more information when throwing PageNotFoundException

### PR DESCRIPTION
**Pull request by aschempp**
Related to https://github.com/contao/core/issues/8009

### CODE REVIEW

**Comment by leofeyer** [comment]
The purpose of contao/core#8009 was to get rid of some log entries, not to double them by logging them in `tl_log` and the `app/logs/prod.log` :)

**Comment by aschempp** [comment]
I know. Now you simply have to remove `$this->log()` and the full message will be preserved ;-)

**Comment by aschempp** [comment]
I have rebased this on the latest develop branch.

**Comment by leofeyer** [comment]
Since we are already logging the exceptions, we should remove the `$this->log()` calls entirely IMHO. But let's discuss it before you spend more time working on it.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 28th, we want to add the additional information such as `url` and `referer` to the log context.

**Comment by leofeyer** [comment]
Sadly, it does not work. The [line formatter](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php#L136) does not consider any additional data that the extension might have. So we are back at adding the context to the exception message, but that does not look too good:

**Comment by Toflar** [comment]
Since when is the formatting of an exception relevant?

**Comment by leofeyer** [comment]
Implemented as discussed in 0f8f51b5950ce7af4fa2812de9a547650a356c83.

**Pull request closed without merging**
